name: Build Scan Upload
description: Build and push an image, run Trivy, prepare SARIF fallback, and upload SARIF.

inputs:
  enabled:
    description: Whether to execute this component flow (true/false).
    required: true
  dockerfile:
    description: Dockerfile path relative to repository root.
    required: true
  image_ref:
    description: Full image reference (registry/repo:tag).
    required: true
  cache_scope:
    description: GHA cache scope identifier for Docker build cache.
    required: true
  trivy_output:
    description: Output SARIF filename (relative to workspace root).
    required: true
  sarif_category:
    description: Code scanning SARIF category.
    required: true
  pull:
    description: Whether Docker build should pull base images (true/false).
    required: false
    default: "true"
  push:
    description: Whether Docker build should push the built image (true/false).
    required: false
    default: "true"
  load:
    description: Whether Docker build should load image into local Docker (true/false).
    required: false
    default: "false"
  upload_sarif:
    description: Whether SARIF upload should run (true/false).
    required: false
    default: "true"

outputs:
  build_outcome:
    description: Outcome of docker build step.
    value: ${{ steps.outcomes.outputs.build_outcome }}
  scan_outcome:
    description: Outcome of Trivy scan step.
    value: ${{ steps.outcomes.outputs.scan_outcome }}

runs:
  using: composite
  steps:
    - name: Build & push image
      id: docker_build
      if: ${{ inputs.enabled == 'true' }}
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
      with:
        context: ./app
        file: ${{ inputs.dockerfile }}
        pull: ${{ inputs.pull }}
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ inputs.image_ref }}
        cache-from: type=gha,scope=${{ inputs.cache_scope }}
        cache-to: type=gha,mode=max,scope=${{ inputs.cache_scope }},ignore-error=true

    - name: Trivy scan image -> SARIF
      id: trivy_scan
      if: ${{ inputs.enabled == 'true' }}
      continue-on-error: true
      uses: aquasecurity/trivy-action@b2933f565dbc598b29947660e66259e3c7bc8561 # 0.20.0
      with:
        image-ref: ${{ inputs.image_ref }}
        ignore-unfixed: true
        severity: HIGH,CRITICAL
        format: sarif
        output: ${{ inputs.trivy_output }}
        exit-code: "0"

    - name: Prepare Trivy SARIF
      id: trivy_sarif
      if: ${{ inputs.enabled == 'true' }}
      shell: bash
      env:
        TRIVY_SARIF_FILE: ${{ github.workspace }}/${{ inputs.trivy_output }}
        TRIVY_SCAN_OUTCOME: ${{ steps.trivy_scan.outcome }}
      run: bash "${{ github.workspace }}/scripts/ci/prepare_trivy_sarif.sh"

    - name: Upload Trivy SARIF
      if: ${{ inputs.enabled == 'true' && inputs.upload_sarif == 'true' && steps.trivy_sarif.outputs.found == 'true' }}
      uses: github/codeql-action/upload-sarif@58d4c8134bcf8ae089f888d056501755e0da2b44 # v4
      with:
        sarif_file: ${{ steps.trivy_sarif.outputs.sarif_file }}
        category: ${{ inputs.sarif_category }}

    - name: Export outcomes
      id: outcomes
      if: ${{ always() }}
      shell: bash
      env:
        FLOW_ENABLED: ${{ inputs.enabled }}
        BUILD_STEP_OUTCOME: ${{ steps.docker_build.outcome }}
        SCAN_STEP_OUTCOME: ${{ steps.trivy_scan.outcome }}
      run: |
        if [[ "${FLOW_ENABLED}" == "true" ]]; then
          echo "build_outcome=${BUILD_STEP_OUTCOME:-skipped}" >> "${GITHUB_OUTPUT}"
          echo "scan_outcome=${SCAN_STEP_OUTCOME:-skipped}" >> "${GITHUB_OUTPUT}"
        else
          echo "build_outcome=skipped" >> "${GITHUB_OUTPUT}"
          echo "scan_outcome=skipped" >> "${GITHUB_OUTPUT}"
        fi
