name: Bug report
description: Report a reproducible defect.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail for someone else to reproduce quickly.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: List the exact steps to reproduce.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots
      description: Paste relevant logs, stack traces, screenshots, or CI links.
      render: shell
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, tooling versions, branch, and any relevant config details.
      placeholder: |
        - OS:
        - Python:
        - Docker:
        - Commit SHA:
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - Low (minor inconvenience)
        - Medium (blocks some workflows)
        - High (blocks major workflows)
        - Critical (security/data loss/outage risk)
    validations:
      required: true
